### ISSUE TITLE
orefs.py crashes

### ISSUE THREAD

**Issue by LAfricain** [adyeths/u2o#66]
Running orefs.py the first time for the config file generation give this issue:
```
orefs.py -v -c RefNd -i ndebele.osis.xml -o ndebele.osis.ref.xml
Reading input file ndebele.osis.xml ...
Getting book names and abbreviations...
Using config file for abbreviations...
Traceback (most recent call last):
  File "/home/cyrille/.bin/orefs.py", line 523, in <module>
    main()
  File "/home/cyrille/.bin/orefs.py", line 519, in main
    processfile(args)
  File "/home/cyrille/.bin/orefs.py", line 441, in processfile
    bookabbrevs, bookabbrevs2 = readconfig(args.c)
  File "/home/cyrille/.bin/orefs.py", line 110, in readconfig
    globals()[i] = config["DEFAULT"][i]
  File "/usr/lib/python3.6/configparser.py", line 1233, in __getitem__
    raise KeyError(key)
KeyError: 'SEPM'
```

**Comment by LAfricain** [comment]
Ok! Please add the right command to the help or the Readme_orefs:
`orefs.py -c create -i OSISFILE -o CONFIG` I search a lot the right command...
