### ISSUE TITLE
Using orefs.py to add osisRef attributes to a translation that has non-Roman numerals

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#75]
Here's an _urgent_ **enhancement** requirement.

How to adapt `orefs.py` for a translation in which the chapter and verse numbers in Scripture references use **non-Roman numerals**?

e.g. The Myanmar numerals: **၀၁၂၃၄၅၆၇၈၉** (U+1040 to U+1049).

Example: USFM
```
\x + \xt ၂မိၤ. ၂၂း၂၈\xt*.\x*
```
which should become in OSIS:
```
<note><reference osisRef="Exod.22.28">၂မိၤ. ၂၂း၂၈</reference>.</note>
```
NB. Although the script is **Myanmar**, the language is actually **Sgaw Karen**.

**Comment by DavidHaslam** [comment]
NB. The solution should be sufficiently ingenious to cover **right to left** scripts as well as **left to right** scripts. 

i.e. So that we can also process translations written in the Arabic/Persian script.

**Comment by DavidHaslam** [comment]
FYI. See [List of numbers in various languages](https://en.wikipedia.org/wiki/List_of_numbers_in_various_languages).

**Comment by adyeths** [comment]
I could potentially add an optional key to the orefs config file that could be set to the numeric digits to use instead of arabic numerals. Something like `digits = ၀၁၂၃၄၅၆၇၈၉` in the default section.

Since I only speak and read English, this is the only way I can think of to do something like this. Does this sound like a workable solution?

**Comment by DavidHaslam** [comment]
Yes - I think that would work. 

Does `\d` in Python match Unicode digits besides `[0-9]` ?

**Comment by DavidHaslam** [comment]
That some of the vernacular book abbreviations might start with a non-Arabic numeral isn’t a problem. They would be already covered by the config file. 

It’s the chapter and verse numbers that need to be tackled.

**Comment by adyeths** [comment]
In python3, the `\d` in a regular expression would match any unicode digit in a string unless ASCII is specified. I'm not going to use regular expressions for this, though.

**Comment by LAfricain** [comment]
Hello,
I tested this new nice feature, but currentlty it doesn't work. I have this issue:
```
orefs.py -v -i cbcm.osis.xml -o cbcm-ref.osis.xml -c cbcmRef 
Reading input file cbcm.osis.xml ...
Getting book names and abbreviations...
Using config file for abbreviations...
Processing cross references...
Traceback (most recent call last):
  File "/home/cyrille/.bin/orefs.py", line 531, in <module>
    main()
  File "/home/cyrille/.bin/orefs.py", line 527, in main
    processfile(args)
  File "/home/cyrille/.bin/orefs.py", line 457, in processfile
    text = processreferences(text, bookabbrevs, bookabbrevs2)
  File "/home/cyrille/.bin/orefs.py", line 217, in processreferences
    lines[i] = reftag.sub(simplerepl, lines[i], 0)
  File "/home/cyrille/.bin/orefs.py", line 189, in simplerepl
    osisrefs, oreferror = getosisrefs(text, currentbook, abbr, abbr2)
  File "/home/cyrille/.bin/orefs.py", line 348, in getosisrefs
    elif abbr2[bkref] in ONECHAP:
KeyError: '၀၇၇'
```
I tried also with only one book (Mattheuw) I have the same issue with KeyError, but the "number" following the KeyErrror, is different.
This is the config file generated by orefs: [cbcmRef.zip](https://github.com/adyeths/u2o/files/3569498/cbcmRef.zip)

Thanks for help.
